### ISSUE TITLE
ERC-TO-NATIVE: extend limits functionality

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#110]
The current implementation of the bridge contracts in `erc-to-native` mode allows to an user to operates within specified limits (daily limit and limits per transaction). But it still allows to operates bridge validators without any limitation. So, if a set of validators will be compromised it could lead to a situation when funds locked on the bridge can be released by sending signatures of compromised validators.

In order to reduce the risk of the attack it is recommended to extend the functionality of limits.

So, we will have the following parameters on both bridges side:
**for Home:**
  HOME_DAILY_LIMIT - maximum number of coins that can be burnt daily
  HOME_MAX_AMOUNT_PER_TX - maximum number of coins that can be burnt in one transaction
  HOME_MIN_AMOUNT_PER_TX - minimum number of coins that can be burnt in one transaction
  FOREIGN_DAILY_LIMIT - maximum number of coins that can be **minted** daily
  FOREIGN_MAX_AMOUNT_PER_TX - maximum number of coins that can be **minted** in one transaction

**for Foreign:**
  FOREIGN_MAX_AMOUNT_PER_TX - maximum number of tokens that can be **locked** in one transaction - to be used by the Bridge UI (or a contract in the Foreign network) to inform users that the value of the bridge transfer is above the limit. 
  HOME_DAILY_LIMIT - maximum number of tokens that can be **unlocked** daily
  HOME_MAX_AMOUNT_PER_TX - maximum number of tokens that can be **unlocked** in one transaction

The functionality for `HOME_DAILY_LIMIT`, `HOME_MAX_AMOUNT_PER_TX` and `HOME_MIN_AMOUNT_PER_TX` already exists in the HomeBridge contract
Implementation of the function `executeAffirmation` needs to be changed as so it does not accept incoming requests if they are above `FOREIGN_DAILY_LIMIT` and `FOREIGN_MAX_AMOUNT_PER_TX` limits. Instead of this the value of the assets must be stored in a variable. This variable will be used by the Bridge Monitor to calculate the balance difference properly. An event (e.g. `DailyLimitExceeded` or `MaxAmountLimitExceeded`) must be raised to notify that the operation was not successful. 

So far there is no functionality covering limits in the ForeignBridge contract.
The following function needs to be changed:
https://github.com/poanetwork/poa-bridge-contracts/blob/1f61c695df23b2a8f79d96e138c6bb5d8cd5b592/contracts/upgradeable_contracts/BasicForeignBridge.sol#L13-L25
to check that the `executeSignatures` operation is still within limits set in `HOME_DAILY_LIMIT` and `HOME_MAX_AMOUNT_PER_TX`. The check should be done prior to checking the operation for duplicates.

The changes must be done based on the code based on https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.1.0.

The suggested changes must be applicable for `erc20-to-erc20` mode of the bridge.

**Comment by patitonar** [comment]
@akolotov Should we introduce a `FOREIGN_DAILY_LIMIT` for **Foreign** too? It could be used by Bridge UI in the same way as `FOREIGN_MAX_AMOUNT_PER_TX` to prevent users from making the transfer since the native coins won't be minted.

**Comment by patitonar** [comment]
> Implementation of the function executeAffirmation needs to be changed as so it does not accept incoming requests if they are above FOREIGN_DAILY_LIMIT and FOREIGN_MAX_AMOUNT_PER_TX limits. Instead of this the value of the assets must be stored in a variable. This variable will be used by the Bridge Monitor to calculate the balance difference properly. An event (e.g. DailyLimitExceeded or MaxAmountLimitExceeded) must be raised to notify that the operation was not successful.

That means that if value of the request is above `FOREIGN_DAILY_LIMIT` or `FOREIGN_MAX_AMOUNT_PER_TX` limits, the affirmation should not be performed, but transaction won't be reverted. Instead, we should accumulate the value amount on a variable and emit an event about limits exceeded.
@akolotov Is this correct?

In that case, for Bridge Monitor the events emitted may help to catch this situation. But about the variable, unless I'm missing something what I understand is that it will accumulate total amount of the failed attempt to execute affirmations, so I don't fully understand how it will help the Monitor to calculate the balance difference since balance wasn't affected by the transaction.

**Comment by akolotov** [comment]
> That means that if value of the request is above FOREIGN_DAILY_LIMIT or FOREIGN_MAX_AMOUNT_PER_TX limits, the affirmation should not be performed, but transaction won't be reverted. Instead, we should accumulate the value amount on a variable and emit an event about limits exceeded.

Correct.

>In that case, for Bridge Monitor the events emitted may help to catch this situation. But about the variable, unless I'm missing something what I understand is that it will accumulate total amount of the failed attempt to execute affirmations, so I don't fully understand how it will help the Monitor to calculate the balance difference since balance wasn't affected by the transaction.

Imagine that we have the following sequence of locking tokens on the Foreign side assuming that the limit per transaction is 300:
1. Alice sent 50 tokens to the bridge account
2. Bob sent 350 tokens to the bridge account 
3. Clare sent 100 tokens to the bridge account 
4. Dylan sent 400 tokens to the bridge account 
So, the balance of the bridge account is 900 tokens.
At the same time only 150 coins were minted since the rest of operations is above the limit.
If we keep 750 in the storage on the Home side, we can always calculate that the balance on the Foreign side must be 150 rather than 900. By doing this the monitor could identify if the balance differs due to incorrect users actions or due to transactions missed by the bridge instances.

**Comment by akolotov** [comment]
correct

**Comment by akolotov** [comment]
Addressed in #117
