### ISSUE TITLE
deployment failing 

### ISSUE THREAD

**Issue by harsh-98** [poanetwork/poa-bridge-contracts#120]
I am currently trying to deploy this application on local testnet.
But the `node deploy.js` is failing because of the condition.
https://github.com/poanetwork/poa-bridge-contracts/blob/master/deploy/src/deploymentUtils.js#L49 
And without it, deployment is successful and blocks mined with those transactions are there.

**Comment by akolotov** [comment]
Please use the branch`develop` that contains the version of the deployment scripts with correct behavior:
https://github.com/poanetwork/poa-bridge-contracts/blob/30bfcc145b2bb2b8028ac5a9becf7a5c077652f5/deploy/src/deploymentUtils.js#L49
