### ISSUE TITLE
Update deploy scripts to deploy rewardable contracts for ERC-to-NATIVE mode

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/poa-bridge-contracts#124]
Update scripts to properly update changes in existing contracts and deploy `FeeManager` related contracts.

Also `.env` file will require a new parameter: `VALIDATORS_REWARD_ACCOUNTS`

**Comment by akolotov** [comment]
Available in [the release 2.3.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0)
