### ISSUE TITLE
The dotenv package dependency is missing

### ISSUE THREAD

**Issue by vkomenda** [poanetwork/poa-bridge-contracts#145]
`deploy/testenv-deploy.js` does not run if there is no system-wide installation of `dotenv`. This can be fixed by adding the `dotenv` dependency in `package.json`. It's pretty simple and I tried to submit a PR for that but it looks I don't have the required rights.

**Comment by patitonar** [comment]
Hi @vkomenda, `dotenv` package dependency is declared on `deploy/package.json`. Have you tried running `npm install` from `deploy` directory?

I think README is not very explicit about this. An idea could be to add a `postinstall` script on root `package.json` that run `npm install` on `deploy` directory too. So in that way, user will have to run only one time `npm install` on root folder

**Comment by vkomenda** [comment]
Thanks for the correction! Indeed I wasn't running the script from the correct working directory.
