### ISSUE TITLE
Refactor distributeFeeProportionally method on BaseFeeManager

### ISSUE THREAD

**Issue by patitonar** [poanetwork/poa-bridge-contracts#163]
We can reduce the number of iterations to get the list of validators and distribute the fees. See this [comment](https://github.com/poanetwork/poa-bridge-contracts/pull/161#discussion_r266012183)

**Comment by akolotov** [comment]
Available in [the release 2.3.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0)
