### ISSUE TITLE
Emit new events for rewards distributed to validators on transfers

### ISSUE THREAD

**Issue by patitonar** [poanetwork/poa-bridge-contracts#170]
This will help to simplify logic to get statistic of collected fees and avoid duplicating logic from the contracts.

See this comments https://github.com/poanetwork/bridge-ui/pull/211#discussion_r274860130

**Comment by akolotov** [comment]
Available in [the release 2.3.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0)
