### ISSUE TITLE
ERC677 support on the Foreign side in the erc20-to-erc20 bridge mode

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#175]
Current implementation of the `erc20-to-erc20` bridge mode assumes that pure ERC20 token is used on the Foreign side. So, when the tokens are relayed to the Home side, the method `transfer` is invoked by the user and the relay request is handled by the TokenBridge oracle without involvement the bridge contract on the Foreign side. It is inconvenient due to following:
- there is no way to revert the request if it exceeds the limits.
- there is no way to halt the bridge operations

Historically, such kind of functionality was suggested for already deployed ERC20 tokens to enhance them through the bridging ability and described shortcomings were considered as insignificant in comparison with the value such solution could bring. But for there are the cases for the bridge when it is going to be used with just deployed tokens. In this case the token could be extended by ERC677 standard in order to address issues described above. 

That's why the bridge contracts working in `erc20-to-erc20` mode could be improved to operate with ERC677 tokens. In order to achieve this the corresponding foreign bridge contract should be extended with support of `onTokenTransfer` method which will raise the `UserRequestForAffirmation` event.

**Comment by akolotov** [comment]
Since it is very important for the token bridge oracle to run correct watcher it is necessary to avoid situations when the tokens could be sent to the bridge contracts with and without usage of `onTokenTransfer`. It is suggested to implement the following:
- to introduce a new parameter `ERC20_EXTENDED_BY_ERC677`
- to check on the contracts deployment stage if the token contract has the `bridgeContract` method. If the method is implemented and `ERC20_EXTENDED_BY_ERC677` is true - proceed with the deployment. If the method does not exist but `ERC20_EXTENDED_BY_ERC677` is true - fail the deployment process. If the method does not exist and `ERC20_EXTENDED_BY_ERC677` is false or not configured - proceed with the deployment.

**Comment by patitonar** [comment]
Do we really need `ERC20_EXTENDED_BY_ERC677`?
Unless I'm missing something I don't think the deployment script on foreing bridge will be performing differents actions based on this variable.
We can initialize the foreign bridge as it is today adding the min, max and daily limits variables.
If needed, we can check `bridgeContract` on token contract to inform on the logs that limits will/won't be applied to transfers.

**Comment by akolotov** [comment]
My opinion is "yes", we need this parameter. It could protect us from the scenarios when the erc20 token on the foreign side have the `bridgeContract` method but the token is not going to be used as ERC677. Especially this is important since the only way to check if the method `bridgeContract` exists is to use it's descriptor which is only 4 bytes length (4 bytes from keccak of the method's ABI). It means that there is non-zero probability that  another method could have the same descriptor. We also cannot relay on the returned value of the method since the bridge contract is not registered at this moment in the token. That's why I would prefer to explicitly specify which kind of token is going to be used as so the deployment process could decide which type of the foreign bridge contract should be deployed: with `onTokenTransfer` functionality or not, should we spend gas to pass limits to the method `initialize` and to store limits or not.

Please note that we cannot use `ERC677Bridge.sol` in the foreign bridge contract since the `onTokenTransfer` method burns the tokens there, whereas we don't need to do this in case of `erc20-to-erc20` bridge mode.

**Comment by akolotov** [comment]
Available in [the release 2.3.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0)
