### ISSUE TITLE
Limit possible loop iterations in "initialize" of BridgeValidators

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#237]
As per the security audit there is a recommendation to explicitly limit the number of iterations assuming that it is not possible to initialize the contract with the number of validators greater than X:

https://github.com/poanetwork/poa-bridge-contracts/blob/786be68cd69526e561dd5654844ac373cda7a539/contracts/upgradeable_contracts/BridgeValidators.sol#L22-L40

Consider to investigate how many validatiors could be handled by `initialize` method if gas limit of the transaction is 75% of maximum block size.

**Comment by akolotov** [comment]
The same is needed to be done for the `RewardableValidators` contract as well.

**Comment by patitonar** [comment]
Looking at the last blocks on mainnet, the max block gas limit is `8.000.000`. So 75% would be `6.000.000`. I run some tests with the following results:

Method: **BridgeValidators initialize**

Validators | Gas used
------------ | -------------
5 | 306.871
20 | 785.992
50 | 1.744.404
100 | 3.342.213
150 | 4.940.776
175 | 5.740.100

Method: **RewardableValidators initialize**

Validators | Gas used
------------ | -------------
5 | 421.434
20 | 1.241.570
50 | 2.882.941
100 | 5.619.019
150 | Out of Gas
175 | Out of Gas


Should we choose one value for both contracts and add a `require` on the `initialize` methods? Does `50` or `100` makes sense?

**Comment by akolotov** [comment]
Thanks! Let's limit both to have 100 validators maximum.

**Comment by akolotov** [comment]
Included in [TokenBridge contracts 2.3.3](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.3)
