### ISSUE TITLE
Add an ability to calculate actual gas usage prior to send deployment transactions

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#26]
Currently `gas limit` is hardcoded:

https://github.com/poanetwork/poa-bridge-contracts/blob/8cf94e4b8b9651d163f15a135ea7f8841b5d2d46/deploy/src/deploymentUtils.js#L54

For example, it causes fail on Ropsten.

**Comment by rstormsf** [comment]
fixed #27
