### ISSUE TITLE
optimize gas usage

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge-contracts#29]
https://github.com/zeppelinos/zos-lib/blob/master/contracts/upgradeability/Proxy.sol

current:
https://github.com/poanetwork/poa-bridge-contracts/blob/8cf94e4b8b9651d163f15a135ea7f8841b5d2d46/contracts/upgradeability/Proxy.sol#L20-L36

needs to be
https://github.com/zeppelinos/zos-lib/blob/a1f057d83958a329353ad0ca248a14f28fbfb04f/contracts/upgradeability/Proxy.sol#L18-L31

```solidity
  function () payable public {
    address _impl = implementation();

    assembly {
      let ptr := mload(0x40)
      calldatacopy(ptr, 0, calldatasize)
      let result := delegatecall(gas, _impl, ptr, calldatasize, 0, 0)
      returndatacopy(ptr, 0, returndatasize)

      switch result
      case 0 { revert(ptr, returndatasize) }
      default { return(ptr, returndatasize) }
    }
  }
```

**Comment by wadeAlexC** [comment]
Looks good to me @rstormsf
