### ISSUE TITLE
(Istanbul HF) Review bridge's smart contracts code because of EIP-1884

### ISSUE THREAD

**Issue by varasev** [poanetwork/poa-bridge-contracts#293]
The upcoming Istanbul hard fork assumes that some of the opcodes will cost higher (especially, `SLOAD` which gas cost is increased from `200` to `800`): https://eips.ethereum.org/EIPS/eip-1884

Seems we need to review our contracts on subject of gas consumption to make sure nothing will be broken there after the HF.

**Comment by akolotov** [comment]
The issue could be applicable for the contracts that have the payable fallback method and assume that it could be called by other contracts. In the current token bridge contracts for `native-to-erc20` and `erc20-to-native` scenarios only EOAs interact with the bridge by sending native tokens (and invoking the fallback method). So, nothing needs to be addressed.
