### ISSUE TITLE
V2 architecture

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge-contracts#37]
Here is what I think how V2 needs to work:

Deposits:

1. When users send POA on Home side,
`Deposit` event is emitted
2. Validators send `signForDeposit` on Home side
3. When enough signatures are collected, bridge operator sends `deposit` public method with all signatures on Foreign side which `mints` the token
it should emit event `CollectedSignaturesForDeposit`

Withdrawals:

1. User sends token to Foreign contract side
2. Emits `Withdrawal` event
3. Validators call `withdraw` on Home side and when enough signatures are collected, it automatically withdrawals coins to the recipient similar to how `deposit` is made right now on foreign side

**Comment by akolotov** [comment]
Thanks! Let's link it with https://github.com/poanetwork/poa-bridge/issues/5

**Comment by rstormsf** [comment]
it's completed in refactor_v1
