### ISSUE TITLE
Upload bridge ABIs to poa specs

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#38]
May, 10th is official start of POA bridge service. So, it is necessary to upload all ABIs related to the bridge service to https://github.com/poanetwork/poa-chain-spec repo:
* Home bridge contract ABI
* Foreign bridge contract ABI
* Validator bridge contract ABI
* Upgradability contract ABI
* Multisig wallet contract ABI
* etc.

**Comment by rstormsf** [comment]
@akolotov 
is this still relevant?

**Comment by akolotov** [comment]
Yes, I think we need to have stored the production version of bridge contracts ABI without necessity to compile contracts as so everyone could implement a Dapp which could interact with our contracts.

**Comment by akolotov** [comment]
The ABIs were published as part of https://github.com/poanetwork/poa-chain-spec/pull/98.
