### ISSUE TITLE
More untied names for `deposit()` and `withdraw()`

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#44]
The current naming for functions to initiate assets transfer from one chain to another is too tied to specific scenario:
* `deposit()` is to send confirmation that POA coins can be moved from `Home` to `Foreign` as POA20 tokens;
* `withdraw()` to send confirmation that POA20 tokens can be returned back from `Foreign` to `Home` as POA coins.

These names could start confusing developers if the same methods are used for transfer an ERC20 token on one network to ERC20 token on another network since scenario could assume transferring the ERC20 token from Ethereum Foundation network to POA network - actual deposit happens on the right side in this case whereas the logic of the bridge will be completely the same. 

That's why it makes sense to consider to rename `deposit()` and `withdraw()` as well as the corresponding event to have more common name e.g. `sendConfirmation` and `sendConfirmationsSet` for methods and `ConfirmationRequired()` for events.

**Comment by rstormsf** [comment]
I think it's done in `refactor_v1` 
@akolotov

**Comment by akolotov** [comment]
Right. Thanks!
