### ISSUE TITLE
Throws error when I put my sidechain's URL instead of sokol in .env file

### ISSUE THREAD

**Issue by kpulkit29** [poanetwork/poa-bridge-contracts#62]
Working fine when home network is sokol
Here is the error
deploying storage for home validators
TypeError: Cannot read property 'length' of undefined
    at sendNodeRequest (/Users/pulkit29/Desktop/check/devchain/poa-bridge-contracts/deploy/src/deploymentUtils.js:88:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:87370) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at deployContract (/Users/pulkit29/Desktop/check/devchain/poa-bridge-contracts/deploy/src/deploymentUtils.js:41:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:87370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asyncfunction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:87370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by akolotov** [comment]
Is URL you are specifying in `.env` is a JSON RPC interface to your chain?

**Comment by kpulkit29** [comment]
Yes I just added my sidechain url in home bridge url in .env file

**Comment by kpulkit29** [comment]
Yes it is the json rpc interface

**Comment by akolotov** [comment]
Is this a public available URL?

**Comment by kpulkit29** [comment]
I was first testing using parity chain http://127.0.0.1:8545
<https://rb.tc/3KA2H#http://127.0.0.1:8545>

**Comment by kpulkit29** [comment]
Then tested using my sidechain rpc endpoint

**Comment by akolotov** [comment]
Could you run the following line on the same terminal where you ran deployment script?

`curl --data '{"method":"net_version","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.0.1:8545`

**Comment by kpulkit29** [comment]
did it still not working

**Comment by kpulkit29** [comment]
https://chain.springrole.com is my sidechain url

**Comment by akolotov** [comment]
A correct JSON response were displayed by running of this command. Right?

**Comment by kpulkit29** [comment]
This curl command was executed correctly but contracts are not being
deployed

**Comment by akolotov** [comment]
DNS record for this URL (`https://chain.springrole.com/`) is not correct. It targets to `http://0.0.0.0:8180/`. Not sure how your system is configured. Please double check.

Could you send `.env` file as well.

**Comment by kpulkit29** [comment]
here is the .env file
DEPLOYMENT_ACCOUNT_ADDRESS=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
DEPLOYMENT_ACCOUNT_PRIVATE_KEY=
DEPLOYMENT_GAS_LIMIT=4000001
DEPLOYMENT_GAS_PRICE=10
GET_RECEIPT_INTERVAL_IN_MILLISECONDS=3000

HOME_RPC_URL=https://chain.springrole.com
HOME_OWNER_MULTISIG=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
HOME_UPGRADEABLE_ADMIN_VALIDATORS=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
HOME_UPGRADEABLE_ADMIN_BRIDGE=0xe53AdA4fE62C8972890d75cbc4C4d2fe6317e84D
HOME_DAILY_LIMIT=30000000000000000000000000
HOME_MAX_AMOUNT_PER_TX=1500000000000000000000000
HOME_MIN_AMOUNT_PER_TX=500000000000000000
HOME_REQUIRED_BLOCK_CONFIRMATIONS=1
HOME_GAS_PRICE=1

FOREIGN_RPC_URL=https://kovan.infura.io/mew
FOREIGN_OWNER_MULTISIG=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
FOREIGN_UPGRADEABLE_ADMIN_VALIDATORS=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
FOREIGN_UPGRADEABLE_ADMIN_BRIDGE=0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a
FOREIGN_DAILY_LIMIT=1000000000000000000
FOREIGN_MAX_AMOUNT_PER_TX=100000000000000000
FOREIGN_MIN_AMOUNT_PER_TX=10000000000000000
FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS=8
FOREIGN_GAS_PRICE=1

REQUIRED_NUMBER_OF_VALIDATORS=1
VALIDATORS="0xD6463bFEAe7b1fE3Ed85467Fd239FeD596F3AD8a"

**Comment by akolotov** [comment]
Did you try to use `http://127.0.0.1:8545` instead of `https://chain.springrole.com`?

**Comment by kpulkit29** [comment]
Yes does not work

**Comment by vinay035** [comment]
@akolotov https://chain.springrole.com is the direct JSON RPC url. It works well in metamask and other web3 providers for transaction.

**Comment by fvictorio** [comment]
Hi @kpulkit29. Two things you could check:

1) Make sure that the private key in the `.env` file is the correct one for that address.
2) Check that the private key doesn't have the `0x` prefix.

**Comment by kpulkit29** [comment]
Yes I checked it its working on sokol network

**Comment by fvictorio** [comment]
I see. How can I test this on my end? Do you have a testnet with a faucet?

**Comment by kpulkit29** [comment]
Don't have any test net but u cam test it by putting on my side chain link
https://chain.springrole.com

On 7 Aug 2018 19:27, "Franco Victorio" <notifications@github.com> wrote:

I see. How can I test this on my end? Do you have a testnet with a faucet?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/poanetwork/poa-bridge-contracts/issues/62#issuecomment-411065312>,
or mute the thread

**Comment by kpulkit29** [comment]
The bridge  works fine with sokol as home network

**Comment by fvictorio** [comment]
I will need an address with some balance to test it, since the script deploys contracts on both networks. If you can, send me some coins to `0xbB73eb2da7530b94C68F33af181FC2487070515a` and I will give it a try.

**Comment by fvictorio** [comment]
Oh, cool, I'll give it a try then.

**Comment by fvictorio** [comment]
I used 0 as gasPrice but I still can't send a transaction:

```
{ jsonrpc: '2.0',
  error: 
   { code: -32010,
     message: 'Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 192000000 and got: 0.' },
  id: 1 }
```

Is there a chance that this is happening to you? I see that the account you are using doesn't have funds either. I don't know why you would need funds if the gas price is 0, but that seems to be happening.

**Comment by kpulkit29** [comment]
The deployment account I mentioned in .env file has funds on both sokol and
kovan

**Comment by akolotov** [comment]
Does it make sense in this case set `DEPLOYMENT_GAS_PRICE=0`?

**Comment by kpulkit29** [comment]
While using our side chain this can be done

**Comment by fvictorio** [comment]
> The deployment account I mentioned in .env file has funds on both sokol and
> kovan

Sorry, I meant that it doesn't have funds in the Spring chain. I'm using a local chain as home and the Spring chain as foreign, and it fails because of lack of funds. I see that in the `.env` that you posted, you are also using that chain, and from what I can tell the deployment address doesn't have funds there.

**Comment by kpulkit29** [comment]
Sir I think my senior will able to answer this better do you mind waiting
for his reply??

**Comment by akolotov** [comment]
I even tried to deploy a test contract from Remix by using Metamask where `https://chain.springrole.com` is set as JSON RPC channel. When I set the gas price for deployment transaction as 0 it was sent successfully but contract deployment failed.

**Comment by vinay035** [comment]
@akolotov @fvictorio Apologies for the delay in reply. I just created a contract via remix it worked well.

Here is the hash which is generated: https://explorer.springrole.com/tx/0x0426e534cd45575dec3c01b789f38f39992d6d3863ccbf7697b1f10375eb1484

What we wanted to achieve is : 
1. Use the side chain as a home chain 
2. Use Kovan as the foreign chain.

So that people can buy token from Kovan and it get converted to ETH in our chain using poa bridge.

**Comment by fvictorio** [comment]
I think what's happening is that your chain has not enabled the byzantium fork, is this possible? The deployment script relies on the `status` field of the transaction receipts, and this only exists after byzantium.

**Comment by vinay035** [comment]
@fvictorio that could be a reason. Let me check and get back to you.

**Comment by vinay035** [comment]
@fvictorio we just checked the status field is present in the getTransactionReceipt.

**Comment by kpulkit29** [comment]
Also after editing the spec.json file according to the byzantium fork.Nothing seems to work.
Status field is present for the private chian I am running.

**Comment by fvictorio** [comment]
> we just checked the status field is present in the getTransactionReceipt

It is present but with a `false` value instead of a `0x01` (confirmed).

> Also after editing the spec.json file according to the byzantium fork.Nothing seems to work.
> Status field is present for the private chian I am running.

You mean you started a private chain with byzantium enabled and couldn't deploy the contracts anyway? I've been able to test the deploy with both parity and geth in the past. Could you share the `spec.json`?

**Comment by kpulkit29** [comment]
The spec file I used is
{
    "name": "DemoPoA",
    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "5",
                "validators" : {
                    "list": ["0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"]
                }
            }
        }
    },
    "params": {
        "gasLimitBoundDivisor": "0x400",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x2323",
        "eip155Transition": 0,
        "validateChainIdTransition": 0,
        "eip140Transition": 0,
        "eip211Transition": 0,
        "eip214Transition": 0,
        "eip658Transition": 0,
        "eip161dTransition": "0x0",
        "eip649Reward": "0x29A2241AF62C0000",
        "eip100bTransition": "0x0",
        "eip649Transition": "0x0"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x5B8D80"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x004ec07d2329997267Ec62b4166639513386F32E": { "balance": "10000000000000000000000" },
        "0000000000000000000000000000000000000005": { "builtin": { "name": "modexp", "activate_at": "0x0", "pricing": { "modexp": { "divisor": 20 } } } },
        "0000000000000000000000000000000000000006": { "builtin": { "name": "alt_bn128_add", "activate_at": "0x0", "pricing": { "linear": { "base": 500, "word": 0 } } } },
        "0000000000000000000000000000000000000007": { "builtin": { "name": "alt_bn128_mul", "activate_at": "0x0", "pricing": { "linear": { "base": 40000, "word": 0 } } } },
        "0000000000000000000000000000000000000008": { "builtin": { "name": "alt_bn128_pairing", "activate_at": "0x0", "pricing": { "alt_bn128_pairing": { "base": 100000, "pair": 80000 } } } }
    }
}

**Comment by fvictorio** [comment]
From what I can tell, you are not initializing any account with funds. Are you using an account with funds for deploying or does this private chain also have gas price 0?

Also, could you tell me which commands are you using to start this private chain?

**Comment by kpulkit29** [comment]
0x004ec07d2329997267Ec62b4166639513386F32E has funds mentioned in the spec file.Moreover funds show up in parity UI as well

**Comment by fvictorio** [comment]
Oh, sorry, I missed that. I will try to do the deploy with that chain.

**Comment by fvictorio** [comment]
I started a chain with that spec (using a variation of the instructions in https://wiki.parity.io/Demo-PoA-tutorial) and I could deploy the bridge contracts without issue.

Could you tell me step by step what are you doing to start that private chain and then to do the deploy?

**Comment by fvictorio** [comment]
Do transactions fail or are they not mined? If they fail, could you paste the error and the transaction receipt? (Enclose the JSON with \`\`\` to preserve the formatting).

**Comment by kpulkit29** [comment]
This error occurs when home bridge url is http://127.0.0.1:8545
and does not occur for sokol network
TypeError: Cannot read property 'length' of undefined
    at sendNodeRequest (/Users/pulkit29/Desktop/check/devchain/poa-bridge-contracts/deploy/src/deploymentUtils.js:88:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1562) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at deployContract (/Users/pulkit29/Desktop/check/devchain/poa-bridge-contracts/deploy/src/deploymentUtils.js:41:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1562) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1562) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kpulkit29** [comment]
I am not able to get the tx hash.This error occurs

**Comment by fvictorio** [comment]
Please, checkout this branch: https://github.com/fvictorio/poa-bridge-contracts/tree/62-deploy-issue-springrole and tell me if the error log changes.

**Comment by kpulkit29** [comment]
I should change the home to my sidechain and foreign to kovan right

**Comment by kpulkit29** [comment]
It is not working for local side json rpc

**Comment by kpulkit29** [comment]
Can we have a hangouts call so that I can share my screen and show you what is exactly happening.

**Comment by akolotov** [comment]
Hi! did you communicate eventually?

**Comment by kpulkit29** [comment]
I had a call with sky he said he would connect me to the right people

**Comment by kpulkit29** [comment]
Can I have a call with you to show exactly what is happening

**Comment by akolotov** [comment]
No more progress on this issue. It is being closed.
