### ISSUE TITLE
A field in bridge contracts to support type of bridge and version tracking 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/poa-bridge-contracts#67]
Currently the bridge contracts does not provide any facility to get information about interfaces supported by particular deployed contract.
The functionality to provide mode of the bridge by contracts will be very useful in order to allow Dapp like `bridge-ui` and `bridge-monitor` (or even `bridge-nodejs`) to adjust automatically their functionality without additional manual configuration.

The functionality to provide list of supported interfaces by the bridge by contracts will be useful in order to load corresponding version of ABIs or turn on/off invocation of corresponding methods from contracts.

So, it make sense to consider to add a method `getBridgeMode()` to return the mode of the bridge and  a method `getBridgeInterfacesVersion()`. An integer value returned by `getBridgeInterfacesVersion()` should be increased manually in the repo every time when backward compatibility is broken: selectors of methods or events were changed, functionality of the methods with the same name and the same list of parameters modified dramatically.

**Comment by rstormsf** [comment]
interesting idea...
I think there was EIP-820 related to registering interfaces like in ERC777 
https://github.com/jacquesd/ERC777/blob/devel/contracts/ERC777ERC20BaseToken.sol#L26

**Comment by akolotov** [comment]
The idea to introduce versioning in contracts is to achieve the following goals:

1. discern contracts deployed to serve different bridge modes.
   At this moment we have two bridge modes: `native-to-erc`, `erc-to-erc`. The plan is to introduce one more type of bridge to relay arbitrary messages.
   The suggestion here is to use 4 bytes of `keccak256` function for the following parameters:
     * `native-to-erc-core` (0x92a8d7fe)
     * `erc-to-erc-core` (0xba4690f5)
     * `arbitrary-message-bridge-core` (0x2544fbb9) 
   `core` is added since the following types of contracts could appear when AMB appears: `native-to-erc-app` and `erc-to-erc-app`. These contracts will interact with AMB.

2. Contracts of the same bridge mode definitely will be changed during the time: new features and bug fixes will be included in the code base. Some changes could 
   even broke backward compatibility with the previous version of the bridge (e.g. the number of method parameters will be changed or their types or name of 
   methods). In order to reduce possible issues appearing when the bridge is up and running, the bridge software needs to have an ability to determine whether it is compatible with particular version of bridge contracts.
   The suggestion here is to have an integer to store the bridge contract version. Decimal notation of this integer will reflect the following:
   ```
   00 00 00
   || || ||
   || ||  the contracts were modified but backward
   || ||  compatibility with particular version of
   || ||  bridge software is preserved
   ||  the number of method parameters or their
   ||  types or name of methods was changed so they
   ||  will work with new version the bridge software
   ||  only
    the contracts and bridge software were re-worked
    significantly (e.g. as it was done when the
    bridge logic was reversed)
   ```
   It make sense to apply the same versioning logic for other contracts used in the bridge project - for example token contracts and validators contract.

**Comment by patitonar** [comment]
@akolotov Here is a proposal for the implementation:
1. Store on `eternalStorage` the 4 bytes of `keccak256` as suggested. The mode will be set on `initialize` method. The method `getBridgeMode()` will return the mode.

2. For the contract version, I would like to suggest using [Semantic Version convention](https://semver.org/).
Given `MAJOR.MINOR.PATCH`, increment:
- MAJOR version when you make incompatible API changes as selectors of methods or events were changed
- MINOR version when you add functionality in a backwards-compatible manner as adding new methods for exposing data
- PATCH version when you make backwards-compatible bug fixes.

We can store the version on the contract state (not on `eternalStorage`, since it is tied to the implemented code) as a struct. Example:
```
struct Version {
    uint64 major;
    uint64 minor;
    uint64 patch;
}
``` 
The method `getBridgeInterfacesVersion()` will return the values of the struct.

**Comment by akolotov** [comment]
@patitonar thanks for proposals.

1. >Store on eternalStorage the 4 bytes of keccak256 as suggested. The mode will be set on initialize method. The method getBridgeMode() will return the mode.

Since we are not going to change the mode of the bridge I don't think we need to keep this value on `eternalStorage`. My suggestion is to have `getBridgeMode()` which will be different for every bridge mode. This method will have `pure` modifier and calculates `keccak256` every time the mode is requested.

Here is example of the method for `native-to-erc` mode:
```solidity
function getBridgeMode() pure public returns(bytes4 _data) {
    returns bytes4(keccak256(abi.encodePacked('native-to-erc-core')));
}
```
This implementation is suggested to be in both `HomeBridgeNativeToErc.sol` and `ForeignBridgeNativeToErc.sol`.

2. I like the idea to use Semantic Version convention. We can move in this direction. We can declare a public variable `getBridgeInterfacesVersion` in `BasicBridge.sol` like this:
```solidity
Version public getBridgeInterfacesVersion = Version(1,0,1);
```
and modify this part of code every time when an up-issue is required.

**Comment by akolotov** [comment]
Addressed in https://github.com/poanetwork/poa-bridge-contracts/pull/80.
