### ISSUE TITLE
change isContract method

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/poa-bridge-contracts#98]
```js
    function isContract(address _addr)
        private
        view
        returns (bool)
    {
        uint length;
        assembly { length := extcodesize(_addr) }
        return length > 0;
    }
```
this method is proven to be broken if attacker calls function from contract in constructor

to fix:
```js
    function isContract(address _addr)
        private
        view
        returns (bool)
    {
       return msg.sender != tx.origin;
    }
```
https://github.com/poanetwork/poa-bridge-contracts/blob/73db89a2f23fdb8a010122fb167bb51954612e9a/contracts/ERC677BridgeToken.sol#L63

**Comment by akolotov** [comment]
Could you describe the scenario in details?
I do not understand how the attacker can call a private function.

**Comment by rstormsf** [comment]
attacker doesn't need to call private function, attacker can be a contract even though you check that it shouldn't be a contract

**Comment by rstormsf** [comment]
never mind since it only calls `to`
